### ISSUE TITLE
兼容npm 7需要的peer升级

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#1]
- [ ] enzyme-adapter-react-16 https://github.com/enzymejs/enzyme/issues/2429
- [x] @ecomfe/eslint-config https://github.com/ecomfe/eslint-config/issues/16
- [x] style-resources-loader https://github.com/yenshih/style-resources-loader/issues/29
- [ ] @pmmmwh/react-refresh-webpack-plugin -> webpack-plugin-serve https://github.com/shellscape/webpack-plugin-serve/issues/195
- [ ] friendly-errors-webpack-plugin https://github.com/geowarin/friendly-errors-webpack-plugin/issues/123
- [ ] webpack-dev-server -> webpack-dev-middleware https://github.com/webpack/webpack-dev-server/issues/2807
